name: ecommerce_yildiz_flutter
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Core
  json_annotation: ^4.8.1
  # Database
  shared_preferences: ^2.2.1
  # Utility
  kartal: ^3.4.1
  responsive_framework: ^1.1.0
  get_it: ^7.6.4
  equatable: ^2.0.5
  # Firebase
  # Route
  auto_route: ^7.8.3
  # Network
  dio: ^5.3.2
  # Language
  easy_localization: ^3.0.3
  flutter_svg: ^2.0.7
  # State Management
  flutter_bloc: ^8.1.3

  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  very_good_analysis: ^5.1.0
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true
  
  assets:
    - assets/image/
    - assets/translations/
    - assets/svg/
    - assets/lottie/

